name: bundlegram
description: A Very Good Project created by Very Good CLI.
version: 1.1.19+20
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^9.0.0
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1 
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.1.0
  intl:
  go_router: ^13.2.0
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.3.3
  dio: ^5.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  carousel_slider: ^5.0.0
  fl_chart: ^0.71.0
  http: ^1.4.0
  retrofit: ^4.4.2
  pretty_dio_logger: ^1.4.0
  url_launcher: ^6.3.1
  device_info_plus: 
  geolocator: ^14.0.2
  network_info_plus: ^6.1.4
  permission_handler: ^12.0.1
  share_plus: ^11.0.0
  flutter_squad_sdk: ^0.0.4
  flutter_dotenv: ^5.2.1
  package_info_plus: ^8.3.0
  webview_flutter: ^4.13.0
  connectivity_plus: ^6.1.5
  image_gallery_saver_plus: ^4.0.1
  fluttertoast: ^8.2.12
  clipboard: ^2.0.2
  firebase_core: ^4.1.0
  flutter_local_notifications: ^19.4.1
  firebase_messaging: ^16.0.1
  local_auth: ^2.3.0
  flutter_staggered_animations: ^1.1.1
  pull_to_refresh: ^2.0.0
  confetti: ^0.8.0
  in_app_update:
  shimmer: ^3.0.0
  toastification: ^3.0.3
  overlay_support: ^2.1.0


dependency_overrides:
  analyzer_plugin: ^0.13.0   # This version supports analyzer 7+

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  riverpod_generator: ^2.3.9
#  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.7
  retrofit_generator: ^9.1.5
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/ic_launcher-playstore.png"
  flavors:
    development:
      image_path: "assets/images/ic_launcher-playstore.png"
    staging:
      image_path: "assets/images/ic_launcher-playstore.png"
    production:
      image_path: "assets/images/ic_launcher-playstore.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/svgs/
    - .env
  fonts:
    - family: MabryPro
      fonts:
        - asset:  fonts/MabryPro-Medium.ttf
    - family: MabryProBold
      fonts:
        - asset:  fonts/MabryPro-Bold.ttf
          weight: 900
    - family: Roboto-Regular
      fonts:
        - asset: fonts/Roboto-Regular.ttf

    - family: Roboto-SemiBold
      fonts:
        - asset: fonts/Roboto-SemiBold.ttf
          weight: 500   
    - family: Roboto-Bold
      fonts:
        - asset: fonts/Roboto-Bold.ttf
          weight: 900
    