// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu_P5Jr24cGAgTXEtdj89q-0vhroibifU',
    appId: '1:199730017351:web:f62dbb3c15d52ced592d62',
    messagingSenderId: '199730017351',
    projectId: 'bundlegram-c601e',
    authDomain: 'bundlegram-c601e.firebaseapp.com',
    storageBucket: 'bundlegram-c601e.firebasestorage.app',
    measurementId: 'G-2D4YCBYDVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB82mJYyuEI-NBNDOlGNxrggy-VCaqlAyg',
    appId: '1:199730017351:android:12e9983921674a09592d62',
    messagingSenderId: '199730017351',
    projectId: 'bundlegram-c601e',
    storageBucket: 'bundlegram-c601e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ8ZsoxGwPkMi_UfDrXFT_h_GtwePLgXo',
    appId: '1:199730017351:ios:cba461ba5b2efda9592d62',
    messagingSenderId: '199730017351',
    projectId: 'bundlegram-c601e',
    storageBucket: 'bundlegram-c601e.firebasestorage.app',
    iosBundleId: 'com.example.verygoodcore.bundlegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ8ZsoxGwPkMi_UfDrXFT_h_GtwePLgXo',
    appId: '1:199730017351:ios:f131253fdedbba7e592d62',
    messagingSenderId: '199730017351',
    projectId: 'bundlegram-c601e',
    storageBucket: 'bundlegram-c601e.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
}
